apiVersion: v1
kind: Pod
metadata:
  name: Task
  labels:
    app: web
spec:
  replicas: 2
  containers:
    – name: task_v1
      image: karannishad/usertimeline
      ports:
        – containerPort: 8080
