apiVersion: v1
kind: Pod
metadata:
  name: usertimeline
  labels:
    app: usertimeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usertimeline
    template:
      metadata:
        labels:
          app: usertimeline
      spec:
        containers:
        – name: usertimeline
          image: karannishad/usertimeline:latest
          ports:
          – containerPort: 8080
